// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Node struct {
	Id              pgtype.UUID
	GroupId         pgtype.UUID
	Name            pgtype.Text
	FirstConnection pgtype.Timestamptz
	LastConnection  pgtype.Timestamptz
}

type Tag struct {
	NodeId pgtype.UUID
	Tag    string
}
