// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTag = `-- name: AddTag :exec

INSERT INTO tags (node_id, tag) VALUES ($1,$2)
`

type AddTagParams struct {
	NodeId pgtype.UUID
	Tag    string
}

func (q *Queries) AddTag(ctx context.Context, arg AddTagParams) error {
	_, err := q.db.Exec(ctx, addTag, arg.NodeId, arg.Tag)
	return err
}

const getNode = `-- name: GetNode :one
SELECT
    id, group_id, name, first_connection, last_connection
FROM
    nodes n
WHERE
    n.id = $1
LIMIT
    1
`

func (q *Queries) GetNode(ctx context.Context, id pgtype.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.Id,
		&i.GroupId,
		&i.Name,
		&i.FirstConnection,
		&i.LastConnection,
	)
	return i, err
}

const getNodes = `-- name: GetNodes :many
SELECT
    id, group_id, name, first_connection, last_connection
FROM
    nodes n
WHERE
    n.group_id = $1
`

func (q *Queries) GetNodes(ctx context.Context, groupID pgtype.UUID) ([]Node, error) {
	rows, err := q.db.Query(ctx, getNodes, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.Id,
			&i.GroupId,
			&i.Name,
			&i.FirstConnection,
			&i.LastConnection,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTags = `-- name: GetTags :many

SELECT t.tag FROM tags t WHERE t.node_id = $1
`

func (q *Queries) GetTags(ctx context.Context, nodeID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getTags, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newNode = `-- name: NewNode :exec
INSERT INTO nodes (id, group_id, name, first_connection, last_connection) 
VALUES ($1, $2, $3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`

type NewNodeParams struct {
	Id      pgtype.UUID
	GroupId pgtype.UUID
	Name    pgtype.Text
}

func (q *Queries) NewNode(ctx context.Context, arg NewNodeParams) error {
	_, err := q.db.Exec(ctx, newNode, arg.Id, arg.GroupId, arg.Name)
	return err
}

const reconnectNode = `-- name: ReconnectNode :exec
UPDATE
    nodes n
SET
    last_connection = CURRENT_TIMESTAMP,
    group_id = $1
WHERE
    n.id = $2
`

type ReconnectNodeParams struct {
	GroupId pgtype.UUID
	Id      pgtype.UUID
}

func (q *Queries) ReconnectNode(ctx context.Context, arg ReconnectNodeParams) error {
	_, err := q.db.Exec(ctx, reconnectNode, arg.GroupId, arg.Id)
	return err
}

const removeTag = `-- name: RemoveTag :exec

DELETE FROM tags t WHERE t.node_id = $1 AND t.tag= $2
`

type RemoveTagParams struct {
	NodeId pgtype.UUID
	Tag    string
}

func (q *Queries) RemoveTag(ctx context.Context, arg RemoveTagParams) error {
	_, err := q.db.Exec(ctx, removeTag, arg.NodeId, arg.Tag)
	return err
}

const updateLastConnection = `-- name: UpdateLastConnection :exec
UPDATE
    nodes n
SET
    last_connection = CURRENT_TIMESTAMP
WHERE
    n.id = $1
`

func (q *Queries) UpdateLastConnection(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastConnection, id)
	return err
}
